2.Partitioned matrices

In [14]:
import numpy as np

#numpy's way of generating a random matrix of a given size
print(np.random.rand(6,6))

[[0.3177023  0.41870987 0.24512839 0.78306648 0.1270157  0.73426178]
 [0.98788529 0.56963833 0.39565783 0.71470309 0.59258129 0.88367835]
 [0.1872055  0.10676959 0.18697827 0.65614251 0.15034277 0.14678591]
 [0.45622889 0.70521531 0.0938537  0.96916034 0.26164054 0.80126019]
 [0.20736256 0.59397275 0.97232222 0.7305967  0.54128399 0.41956275]
 [0.2698817  0.93266172 0.25465483 0.00724655 0.57050343 0.09278105]]


a) Using the MATLAB command round ( 10 *rand ( 6, 6) ) generate two randomly
selected ( 6 x 6) matrices A and B. Compute the product AB. Then write each of A
and B as a block matrix of the form

A = 
$\begin{bmatrix}
    A_1 & A_2\\
    A_3 & A_4
\end{bmatrix}$

B = 
$\begin{bmatrix}
    B_1 & B_2\\
    B_3 & B_4
\end{bmatrix}$

Above, each A1 and B1 should be a (3 x 3) block. Using matrix surgery (see Section 4
of Appendix A) extract the A1 and B1 matrices and form the new block matrix:

AB = 
$\begin{bmatrix}
    A_1B_1 + A_2B_3 & A_1B_2 + A_2B_4\\
    A_3B_1 + A_4B_3 & A_3B_2 + A_4B_4
\end{bmatrix}$


Compare the preceding block matrix with AB and confirm that they are equal.

In [20]:
#randamize A and B
A = np.random.rand(6,6)
B = np.random.rand(6,6)

print ("A= \n",A)
print ("\nB= \n",B)
print ("\nAB= \n",np.dot(A,B))

A= 
 [[0.87730527 0.04430991 0.61254229 0.62226797 0.90133676 0.38112296]
 [0.10519818 0.23826767 0.68581646 0.64988816 0.39108448 0.85104838]
 [0.11796045 0.44977712 0.06856825 0.29112559 0.10010797 0.54904344]
 [0.14383593 0.77914772 0.91724231 0.86366051 0.7960708  0.78816916]
 [0.13271107 0.45290554 0.72833777 0.19404693 0.52850299 0.49754293]
 [0.40137412 0.97687978 0.51362255 0.74330649 0.9876486  0.82663379]]

B= 
 [[0.89216501 0.29109002 0.35287724 0.10611353 0.54729888 0.94693638]
 [0.36233265 0.96881203 0.06428128 0.66596007 0.08200232 0.26643193]
 [0.45738698 0.03535655 0.81132027 0.38152768 0.87672118 0.32750605]
 [0.05241003 0.23539663 0.95354384 0.67235142 0.85850251 0.64171944]
 [0.65365495 0.99549453 0.06758105 0.8216686  0.88419987 0.82633953]
 [0.22471011 0.74037516 0.1141337  0.04330646 0.29412282 0.00318733]]

AB= 
 [[1.78634335 1.64588973 1.50716938 1.53179237 2.46408792 2.18851556]
 [0.97480395 1.45810586 1.35211505 1.22664862 1.83242337 1.13063414]
 [0.50364093 1

In [23]:
#Start of problem defining everything

#A blocks
A1 = [[A[0,0],A[0,1],A[0,2]],
      [A[1,0],A[1,1],A[1,2]],
      [A[2,0],A[2,1],A[2,2]]]

A2 = [[A[0,3],A[0,4],A[0,5]],
      [A[1,3],A[1,4],A[1,5]],
      [A[2,3],A[2,4],A[2,5]]]

A3 = [[A[3,0],A[3,1],A[3,2]],
      [A[4,0],A[4,1],A[4,2]],
      [A[5,0],A[5,1],A[5,2]]]

A4 = [[A[3,3],A[3,4],A[3,5]],
      [A[4,3],A[4,4],A[4,5]],
      [A[5,3],A[5,4],A[5,5]]]

#B blocks
B1 = [[B[0,0],B[0,1],B[0,2]],
      [B[1,0],B[1,1],B[1,2]],
      [B[2,0],B[2,1],B[2,2]]]

B2 = [[B[0,3],B[0,4],B[0,5]],
      [B[1,3],B[1,4],B[1,5]],
      [B[2,3],B[2,4],B[2,5]]]

B3 = [[B[3,0],B[3,1],B[3,2]],
      [B[4,0],B[4,1],B[4,2]],
      [B[5,0],B[5,1],B[5,2]]]

B4 = [[B[3,3],B[3,4],B[3,5]],
      [B[4,3],B[4,4],B[4,5]],
      [B[5,3],B[5,4],B[5,5]]]

In [46]:
# use np.add to add the 2 multiplied matricies
AB1 = np.add(np.dot(A1,B1), np.dot(A2,B3))
AB2 = np.add(np.dot(A1,B2), np.dot(A2,B4))
AB3 = np.add(np.dot(A3,B1), np.dot(A4,B3))
AB4 = np.add(np.dot(A3,B2), np.dot(A4,B4))
# print(AB1)

#initilizes an empty 6x6 matrix
AB_block = np.zeros((6,6))

for i in range(3):
    for j in range(3):
        AB_block[i,j] = AB1[i,j]
        AB_block[i,j+3] = AB2[i,j]
        AB_block[i+3,j] = AB3[i,j]
        AB_block[i+3,j+3] = AB4[i,j]

print("AB from block method\n AB=\n" ,AB_block)
print("\nAB through normal multiplication\n AB=\n", np.dot(A,B))

AB from block method
 AB=
 [[1.78634335 1.64588973 1.50716938 1.53179237 2.46408792 2.18851556]
 [0.97480395 1.45810586 1.35211505 1.22664862 1.83242337 1.13063414]
 [0.50364093 1.04719598 0.4731994  0.6399829  0.66149134 0.52528665]
 [1.57290041 2.4084752  1.81231244 2.15302011 2.62393788 1.85876038]
 [1.08306638 1.44333098 0.94439471 1.17984933 1.52855186 1.04770489]
 [1.81726272 2.85159855 1.49101169 2.23619696 2.50462289 2.10432427]]

AB through normal multiplication
 AB=
 [[1.78634335 1.64588973 1.50716938 1.53179237 2.46408792 2.18851556]
 [0.97480395 1.45810586 1.35211505 1.22664862 1.83242337 1.13063414]
 [0.50364093 1.04719598 0.4731994  0.6399829  0.66149134 0.52528665]
 [1.57290041 2.4084752  1.81231244 2.15302011 2.62393788 1.85876038]
 [1.08306638 1.44333098 0.94439471 1.17984933 1.52855186 1.04770489]
 [1.81726272 2.85159855 1.49101169 2.23619696 2.50462289 2.10432427]]


b) Repeat this calculation on three other matrices (not necessarily (6 x 6) matrices).
Break some of these matrices into blocks of unequal sizes. You need to make sure
that corresponding blocks are the correct size so that matrix multiplication is defined.

In [47]:
#I assume by 3 other it means, A, B, and AB. So im gonna do 3x3

#randamize C and D
C = np.random.rand(3,3)
D = np.random.rand(3,3)

print ("C= \n",C)
print ("\nD= \n",D)
print ("\nCD= \n",np.dot(C,D))

C= 
 [[0.10741933 0.0401007  0.13932469]
 [0.75488004 0.58613515 0.32953784]
 [0.3075913  0.42949935 0.42258834]]

D= 
 [[0.41152523 0.08564739 0.18398238]
 [0.77768723 0.03877271 0.78155667]
 [0.74008683 0.67388658 0.63430076]]

CD= 
 [[0.17850393 0.10464404 0.13947799]
 [1.01036861 0.30945068 0.80600857]
 [0.7733498  0.32777386 0.66031757]]


In [77]:
# C block
C1 = [[C[0,0],C[0,1]],
      [C[1,0],C[1,1]]]

C2 = [[C[0,2]],
      [C[1,2]]]

C3 = [[C[2,0],C[2,1]]]

C4 = [[C[2,2]]]


# D block
D1 = [[D[0,0],D[0,1]],
      [D[1,0],D[1,1]]]

D2 = [[D[0,2]],
      [D[1,2]]]

D3 = [[D[2,0],D[2,1]]]

D4 = [[D[2,2]]]

In [79]:
# use np.add to add the 2 multiplied matricies
CD1 = np.add(np.dot(C1,D1), np.dot(C2,D3))
CD2 = np.add(np.dot(C1,D2), np.dot(C2,D4))
CD3 = np.add(np.dot(C3,D1), np.dot(C4,D3))
CD4 = np.add(np.dot(C3,D2), np.dot(C4,D4))

#initilizes an empty 3x3 matrix
CD_block = np.zeros((3,3))

for i in range(2):
    for j in range(2):
        CD_block[i,j] = CD1[i,j]
        
CD_block[0,2] = CD2[0,0]
CD_block[1,2] = CD2[1,0]

CD_block[2,0] = CD3[0,0]
CD_block[2,1] = CD3[0,1]

CD_block[2,2] = CD4[0,0]

print("CD from block method\n CD=\n" ,CD_block)
print("\nCD through normal multiplication\n CD=\n", np.dot(C,D))

CD from block method
 CD=
 [[0.17850393 0.10464404 0.13947799]
 [1.01036861 0.30945068 0.80600857]
 [0.7733498  0.32777386 0.66031757]]

CD through normal multiplication
 CD=
 [[0.17850393 0.10464404 0.13947799]
 [1.01036861 0.30945068 0.80600857]
 [0.7733498  0.32777386 0.66031757]]


c) Repeat the calculation in (a) with the product of a (2 x 3) block matrix times a
(3 x 3) block matrix.

In [52]:
#randamize E and F
E = np.random.rand(2,3)
F = np.random.rand(3,3)

print ("E= \n",E)
print ("\nF= \n",F)
print ("\nEF= \n",np.dot(E,F))

E= 
 [[0.15135655 0.81821324 0.42734536]
 [0.63402855 0.82193048 0.18602505]]

F= 
 [[0.39139892 0.91777686 0.63770842]
 [0.37852436 0.48707977 0.86060872]
 [0.65318224 0.19845424 0.34368603]]

EF= 
 [[0.64808883 0.62225516 0.94755543]
 [0.68078705 1.0191599  1.17562009]]


In [80]:
# E block
E1 = [[E[0,0],E[0,1]]]

E2 = [[E[0,2]]]

E3 = [E[1,0],E[1,1]]

E4 = [[E[1,2]]]


# D block
F1 = [[F[0,0],F[0,1]],
      [F[1,0],F[1,1]]]

F2 = [[F[0,2]],
      [F[1,2]]]

F3 = [[F[2,0],F[2,1]]]

F4 = [[F[2,2]]]

In [87]:
# use np.add to add the 2 multiplied matricies
EF1 = np.add(np.dot(E1,F1), np.dot(E2,F3))
EF2 = np.add(np.dot(E1,F2), np.dot(E2,F4))
EF3 = np.add(np.dot(E3,F1), np.dot(E4,F3))
EF4 = np.add(np.dot(E3,F2), np.dot(E4,F4))

#initilizes an empty 2x3 matrix
EF_block = np.zeros((2,3))


EF_block[0,0] = EF1[0,0]
EF_block[0,1] = EF1[0,1]
        
EF_block[0,2] = EF2[0,0]

EF_block[1,0] = EF3[0,0]
EF_block[1,1] = EF3[0,1]

EF_block[1,2] = EF4[0,0]

print("EF from block method\n EF=\n" ,EF_block)
print("\nEF through normal multiplication\n EF=\n", np.dot(E,F))

EF from block method
 EF=
 [[0.64808883 0.62225516 0.94755543]
 [0.68078705 1.0191599  1.17562009]]

EF through normal multiplication
 EF=
 [[0.64808883 0.62225516 0.94755543]
 [0.68078705 1.0191599  1.17562009]]
